In [27]:
# fitting affine transformation two 6 sets of points
import numpy as np

A = np.empty((0,6),int)
B = np.array([])
X = np.array([[100, 100], [200, 100], [200, 200]])
X_transformed = np.array([[120, 120], [240, 100], [220, 250]])

for i in range(len(X)):
    A = np.append(A, np.array([[X[i][0],X[i][1],0,0,1,0]]),axis=0)
    A = np.append(A,np.array([[0,0,X[i][0],X[i][1],0,1]]),axis=0)
    B = np.append(B,[X_transformed[i][0],X_transformed[i][1]])

print(A,B.T)

print("Compute affine transformation matrix:")
M = np.linalg.solve(A,B.T)
print(M)

print(np.allclose(np.dot(A, M), B.T))

[[100 100   0   0   1   0]
 [  0   0 100 100   0   1]
 [200 100   0   0   1   0]
 [  0   0 200 100   0   1]
 [200 200   0   0   1   0]
 [  0   0 200 200   0   1]] [120. 120. 240. 100. 220. 250.]
Compute affine transformation matrix:
[  1.2  -0.2  -0.2   1.5  20.  -10. ]
True


In [3]:
print(np.array([1,2,3])/2)
x1,x2 = np.linalg.solve([[1,2],[3,5]],[1,2])
P = np.array([1,2,3,4,5,6]).T
print(P,P.shape)

[0.5 1.  1.5]
[1 2 3 4 5 6] (6,)


In [4]:
# for homography use the medium one

In [14]:
A = np.array([])
A = np.append(A,[[1,2,3,0,0,0,-1,0,0]])
A = np.append(A,[[0,0,0,1,2,3,0,-1,0]])

In [15]:
A

array([ 1.,  2.,  3.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,
        2.,  3.,  0., -1.,  0.])